// <auto-generated />
using DAP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAP.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202121243_ZonesUpdate3")]
    partial class ZonesUpdate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DAP.Server.Models.Dialogue", b =>
                {
                    b.Property<int>("DialogueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DialogueText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogueId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserSceneUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("UserSceneUserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ImageURL = "/images/wire.png",
                            ItemName = "Měďený drát",
                            UserId = 1
                        },
                        new
                        {
                            ItemId = 2,
                            ImageURL = "/images/key1.png",
                            ItemName = "Klíč od radnice",
                            UserId = 1
                        },
                        new
                        {
                            ItemId = 3,
                            ImageURL = "/images/coil.png",
                            ItemName = "Pojistka",
                            UserId = 2
                        },
                        new
                        {
                            ItemId = 4,
                            ImageURL = "/images/key2.png",
                            ItemName = "Klíč od šuplíku",
                            UserId = 3
                        },
                        new
                        {
                            ItemId = 5,
                            ImageURL = "/images/card.png",
                            ItemName = "Karta",
                            UserId = 3
                        },
                        new
                        {
                            ItemId = 6,
                            ImageURL = "/images/mug.png",
                            ItemName = "Hrnek s vodou",
                            UserId = 3
                        },
                        new
                        {
                            ItemId = 7,
                            ImageURL = "/images/levers-comb.png",
                            ItemName = "Lístek s kombinací pák",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAP.Server.Models.Minigame", b =>
                {
                    b.Property<int>("MinigameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinigameDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinigameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneImage")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Scene");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Scene = "Main Menu",
                            SceneImage = "/images/sc0-intro.png"
                        },
                        new
                        {
                            UserId = 2,
                            Scene = "Náměstí",
                            SceneImage = "/images/sc1-square.png"
                        },
                        new
                        {
                            UserId = 3,
                            Scene = "Recepce",
                            SceneImage = "/images/sc2-hall.png"
                        },
                        new
                        {
                            UserId = 4,
                            Scene = "Kancelář",
                            SceneImage = "/images/sc3-office.png"
                        },
                        new
                        {
                            UserId = 5,
                            Scene = "Trezor",
                            SceneImage = "/images/sc4-vault.png"
                        },
                        new
                        {
                            UserId = 6,
                            Scene = "Konec",
                            SceneImage = "/images/sc5-end.png"
                        },
                        new
                        {
                            UserId = 7,
                            Scene = "PhoneOverlay",
                            SceneImage = "/images/phone-overlay.png"
                        },
                        new
                        {
                            UserId = 8,
                            Scene = "DrawerOverlay",
                            SceneImage = "/images/kod.png"
                        },
                        new
                        {
                            UserId = 9,
                            Scene = "LeversOverlay",
                            SceneImage = "/images/levers-bg.png"
                        });
                });

            modelBuilder.Entity("DAP.Server.Models.Zones", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bottom")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Left")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredItem")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserSceneUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("ZoneId");

                    b.HasIndex("UserSceneUserId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            Bottom = 0m,
                            Height = 22m,
                            InteractionName = "wire",
                            InteractionType = "getItem",
                            Left = 6m,
                            UserId = 2,
                            Width = 8m
                        },
                        new
                        {
                            ZoneId = 2,
                            Bottom = 0m,
                            Height = 6m,
                            InteractionName = "klic-od-radnice",
                            InteractionType = "getItem",
                            Left = 35m,
                            RequiredItem = "wire",
                            UserId = 2,
                            Width = 12m
                        },
                        new
                        {
                            ZoneId = 3,
                            Bottom = 33m,
                            Height = 18m,
                            InteractionName = "3",
                            InteractionType = "nextScene",
                            Left = 36m,
                            RequiredItem = "klic-od-radnice",
                            UserId = 2,
                            Width = 7m
                        },
                        new
                        {
                            ZoneId = 4,
                            Bottom = 52m,
                            Height = 26m,
                            InteractionName = "7",
                            InteractionType = "nextScene",
                            Left = 2m,
                            RequiredItem = "coil",
                            UserId = 3,
                            Width = 7m
                        },
                        new
                        {
                            ZoneId = 5,
                            Bottom = 40m,
                            Height = 45m,
                            InteractionName = "3",
                            InteractionType = "nextScene",
                            Left = 82m,
                            UserId = 3,
                            Width = 10m
                        },
                        new
                        {
                            ZoneId = 6,
                            Bottom = 40m,
                            Height = 34m,
                            InteractionName = "coil",
                            InteractionType = "getItem",
                            Left = 62m,
                            UserId = 3,
                            Width = 12m
                        },
                        new
                        {
                            ZoneId = 7,
                            Bottom = 43m,
                            Height = 16m,
                            InteractionName = "levers-comb",
                            InteractionType = "getItem",
                            Left = 17m,
                            UserId = 3,
                            Width = 28m
                        },
                        new
                        {
                            ZoneId = 8,
                            Bottom = 38m,
                            Height = 27m,
                            InteractionName = "klic-od-supliku",
                            InteractionType = "getItem",
                            Left = 5m,
                            UserId = 4,
                            Width = 14m
                        },
                        new
                        {
                            ZoneId = 9,
                            Bottom = 30m,
                            Height = 36m,
                            InteractionName = "card",
                            InteractionType = "getItem",
                            Left = 75m,
                            RequiredItem = "wire",
                            UserId = 4,
                            Width = 18m
                        },
                        new
                        {
                            ZoneId = 10,
                            Bottom = 45m,
                            Height = 15m,
                            InteractionName = "mug",
                            InteractionType = "getItem",
                            Left = 57m,
                            UserId = 4,
                            Width = 7m
                        },
                        new
                        {
                            ZoneId = 11,
                            Bottom = 20m,
                            Height = 15m,
                            InteractionName = "8",
                            InteractionType = "nextScene",
                            Left = 62m,
                            RequiredItem = "klic-od-supliku",
                            UserId = 4,
                            Width = 7m
                        },
                        new
                        {
                            ZoneId = 12,
                            Bottom = 27m,
                            Height = 40m,
                            InteractionName = "leverSwitch",
                            InteractionType = "prepniPaku",
                            Left = 30m,
                            UserId = 9,
                            Width = 5m
                        },
                        new
                        {
                            ZoneId = 13,
                            Bottom = 27m,
                            Height = 40m,
                            InteractionName = "leverSwitch",
                            InteractionType = "prepniPaku",
                            Left = 45m,
                            UserId = 9,
                            Width = 5m
                        },
                        new
                        {
                            ZoneId = 14,
                            Bottom = 27m,
                            Height = 40m,
                            InteractionName = "leverSwitch",
                            InteractionType = "prepniPaku",
                            Left = 60m,
                            UserId = 9,
                            Width = 5m
                        },
                        new
                        {
                            ZoneId = 15,
                            Bottom = 27m,
                            Height = 40m,
                            InteractionName = "leverSwitch",
                            InteractionType = "prepniPaku",
                            Left = 75m,
                            UserId = 9,
                            Width = 5m
                        },
                        new
                        {
                            ZoneId = 16,
                            Bottom = 39m,
                            Height = 13m,
                            InteractionName = "vaultDoors",
                            InteractionType = "finalScene",
                            Left = 72m,
                            RequiredItem = "card",
                            UserId = 5,
                            Width = 6m
                        },
                        new
                        {
                            ZoneId = 17,
                            Bottom = 52m,
                            Height = 15m,
                            InteractionName = "9",
                            InteractionType = "nextScene",
                            Left = 20m,
                            UserId = 5,
                            Width = 15m
                        },
                        new
                        {
                            ZoneId = 18,
                            Bottom = 12m,
                            Height = 38m,
                            InteractionName = "generator",
                            InteractionType = "useItem",
                            Left = 2m,
                            RequiredItem = "mug",
                            UserId = 5,
                            Width = 15m
                        });
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.HasOne("DAP.Server.Models.UserScene", null)
                        .WithMany("Item")
                        .HasForeignKey("UserSceneUserId");
                });

            modelBuilder.Entity("DAP.Server.Models.Zones", b =>
                {
                    b.HasOne("DAP.Server.Models.UserScene", null)
                        .WithMany("Zones")
                        .HasForeignKey("UserSceneUserId");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Navigation("Item");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
