// <auto-generated />
using DAP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAP.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119120532_nevim")]
    partial class nevim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DAP.Server.Models.Dialogue", b =>
                {
                    b.Property<int>("DialogueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DialogueText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogueId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DAP.Server.Models.Minigame", b =>
                {
                    b.Property<int>("MinigameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinigameDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinigameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneImage")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Scene");
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.HasOne("DAP.Server.Models.UserScene", "Scene")
                        .WithMany("Item")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
