// <auto-generated />
using DAP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAP.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119122913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DAP.Server.Models.Dialogue", b =>
                {
                    b.Property<int>("DialogueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DialogueText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogueId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ImageURL = "/images/wire.png",
                            ItemName = "Měďený drát",
                            RoomId = 1
                        },
                        new
                        {
                            ItemId = 2,
                            ImageURL = "/images/key1.png",
                            ItemName = "Klíč od radnice",
                            RoomId = 1
                        },
                        new
                        {
                            ItemId = 3,
                            ImageURL = "/images/coil.png",
                            ItemName = "Pojistka",
                            RoomId = 2
                        },
                        new
                        {
                            ItemId = 4,
                            ImageURL = "/images/key2.png",
                            ItemName = "Klíč od šuplíku",
                            RoomId = 3
                        },
                        new
                        {
                            ItemId = 5,
                            ImageURL = "/images/card.png",
                            ItemName = "Karta",
                            RoomId = 3
                        },
                        new
                        {
                            ItemId = 6,
                            ImageURL = "/images/mug.png",
                            ItemName = "Hrnek s vodou",
                            RoomId = 3
                        },
                        new
                        {
                            ItemId = 7,
                            ImageURL = "/images/levers-comb.png",
                            ItemName = "Lístek s kombinací pák",
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("DAP.Server.Models.Minigame", b =>
                {
                    b.Property<int>("MinigameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinigameDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinigameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneImage")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Scene");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Scene = "Main Menu",
                            SceneImage = "/images/sc0-intro.png"
                        },
                        new
                        {
                            UserId = 2,
                            Scene = "Náměstí",
                            SceneImage = "/images/sc1-square.png"
                        },
                        new
                        {
                            UserId = 3,
                            Scene = "Recepce",
                            SceneImage = "/images/sc2-hall.png"
                        },
                        new
                        {
                            UserId = 4,
                            Scene = "Kancelář",
                            SceneImage = "/images/sc3-office.png"
                        },
                        new
                        {
                            UserId = 5,
                            Scene = "Trezor",
                            SceneImage = "/images/sc4-vault.png"
                        },
                        new
                        {
                            UserId = 6,
                            Scene = "Konec",
                            SceneImage = "/images/sc5-end.png"
                        });
                });

            modelBuilder.Entity("DAP.Server.Models.Item", b =>
                {
                    b.HasOne("DAP.Server.Models.UserScene", "Scene")
                        .WithMany("Item")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("DAP.Server.Models.UserScene", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
